language: python
python:
        - "2.7"
install:
        - "yes | python setup.py install"
        - pip install pep8
script: 
        - git fetch --all
        - git show 0ebce35596234a95f5ddcd1748d726c15e66067e
        - pwd
        - ls
        - pep8 --max-line-length=120 kenja
        - nosetests
        - kenja.historage.convert . /tmp/historage
