language: python
python:
        - "2.7"
install:
        - "yes | python setup.py install"
        - pip install pep8
script: 
        - pep8 --max-line-length=120 kenja
        - nosetests
        - kenja.historage.convert . /tmp/historage
