language: python
python:
        - "2.7"
        - "3.5"
install:
        - "yes | python setup.py install"
        - pip install pep8
script: 
        - pep8 --max-line-length=120 kenja
        - nosetests
