language: python
python:
        - "2.7"
install:
        - "yes | python setup.py install"
        - pip install pep8
script: 
        - git clone https://github.com/niyaton/kenja.git /tmp/kenja
        - pep8 --max-line-length=120 kenja
        - nosetests
        - kenja.historage.convert /tmp/kenja /tmp/historage
